### ISSUE TITLE
When installing the app, I get a validation error.

### ISSUE THREAD

**Issue by Beck-Haywood** [tempor1s/make-checkin#2]
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:259:in `raise_api_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::ValidationFailedError)

**Comment by tempor1s** [comment]
Yep. It is an issue with one of the libraries we are using. Working on fixing and should have something by end of day. Sorry for the the inconvenience!

**Comment by tempor1s** [comment]
Going to revert back to an older version for now, will push keyring encrypted version later :)

**Comment by tempor1s** [comment]
The issue has been fixed. Please upgrade to the newest version, or do a clean install.
